# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76897744683401741cadc5c15c14a22f359478a2ecfe6c4dd2f1d4584a81b66638a85e848bbcbcdea9d38137eff4e78cc6ae801c19284f36b8b5411847f31ce5

test:
  secret_key_base: 1b5a210fb534048408a371e28fc97db43c75e6461867b96c76054aae3f20de9c8a9bdadbf4fe980a6f3d09c5203913ba9aa269050194eb6ccfc3bf299ba2cf9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
